import { Item, ClassDefinition, Rarity, Manufacturer } from '../../types';

function applyManufacturer(item: Item): Item {
  let processed = item;
  if (processed.rarity !== 'common' && random() <= 0.5) {
    const mfs: Manufacturer[] = ['Kinetix', 'AeroDynamics', 'OmniCorp'];
    const manufacturer = mfs[Math.floor(random() * mfs.length)];
    processed = {
      ...processed,
      id: `${processed.id}_${manufacturer}`,
      name: `${manufacturer} ${processed.name}`,
      manufacturer
    };
  }
  return applyHardwareSlots(processed);
}
/**
 * entities/items.ts
 * Definições e validações do sistema de itens e equipamentos.
 */

import { random } from '../engine/rng';
import { CLASSES } from './classes';


export const CIRCUIT_MODULES: Record<string, Item> = {
  mod_overclock: {
    id: 'mod_overclock',
    name: 'Microchip de Overclock',
    type: 'circuit_module',
    rarity: 'rare',
    description: 'Aumenta a frequência base do equipamento. (+5 T-ATK)',
    statModifiers: { atk: 5 },
    value: 50,
    level: 1
  },
  mod_hightension: {
    id: 'mod_hightension',
    name: 'Transistor de Alta Tensão',
    type: 'circuit_module',
    rarity: 'rare',
    description: 'Armazena energia potencial excedente. (+10 Max EP)',
    statModifiers: { mp: 10 },
    value: 50,
    level: 1
  },
  mod_cooling: {
    id: 'mod_cooling',
    name: 'Capacitor de Resfriamento',
    type: 'circuit_module',
    rarity: 'rare',
    description: 'Melhora a dissipação térmica, acelerando as ações. (+3 SPD)',
    statModifiers: { spd: 3 },
    value: 50,
    level: 1
  },
  mod_plating: {
    id: 'mod_plating',
    name: 'Placa de Carbono',
    type: 'circuit_module',
    rarity: 'rare',
    description: 'Adiciona uma camada extra de proteção estrutural. (+5 DEF)',
    statModifiers: { def: 5 },
    value: 50,
    level: 1
  },
  mod_biosynth: {
    id: 'mod_biosynth',
    name: 'Núcleo Biossintético',
    type: 'circuit_module',
    rarity: 'epic',
    description: 'Integra fluidos vitais regenerativos. (+25 Max HP)',
    statModifiers: { hp: 25 },
    value: 150,
    level: 1
  },
  mod_lifesteal: {
    id: 'mod_lifesteal',
    name: 'Extrator Sanguessuga',
    type: 'circuit_module',
    rarity: 'epic',
    description: 'Absorve vitalidade inimiga a cada golpe. (5% Roubo de Vida)',
    passiveEffects: { lifesteal: 0.05 },
    value: 200,
    level: 1
  },
  mod_resistance: {
    id: 'mod_resistance',
    name: 'Filtro de Anomalias',
    type: 'circuit_module',
    rarity: 'epic',
    description: 'Filtra ameaças biológicas e digitais. (50% Res. Status)',
    passiveEffects: { statusResistance: 0.50 },
    value: 200,
    level: 1
  }
};

export function getRandomCircuitModule(floor: number): Item {
  const mods = Object.values(CIRCUIT_MODULES);
  const index = Math.floor(random() * mods.length);
  return { ...mods[index], level: 1 };
}

function applyHardwareSlots(item: Item): Item {
  if (item.type === 'circuit_module' || item.type === 'consumable') return item;
  let slots = 0;
  if (item.rarity === 'rare') slots = 1;
  else if (item.rarity === 'epic') slots = 2;
  
  if (slots > 0 && !item.hardwareSlots) {
    return {
      ...item,
      hardwareSlots: Array(slots).fill(null)
    };
  }
  return item;
}

export const ITEMS_DATABASE: Record<string, Item> = {
  // --- WEAPON ---
  weapon_common_classless_1: {
    id: 'weapon_common_classless_1',
    name: 'Lâmina Enferrujado',
    type: 'weapon',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {atk:10},
    value: 15,
  },
  weapon_common_classless_2: {
    id: 'weapon_common_classless_2',
    name: 'Rifle Padrão',
    type: 'weapon',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {atk:10},
    value: 15,
  },
  weapon_common_classless_3: {
    id: 'weapon_common_classless_3',
    name: 'Disparador Usado',
    type: 'weapon',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {atk:10},
    value: 15,
  },
  weapon_common_tecno_aprendiz: {
    id: 'weapon_common_tecno_aprendiz',
    name: 'Ferramenta de Manutenção Sucateado',
    type: 'weapon',
    rarity: 'common',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {atk:10},
    value: 15,
  },
  weapon_common_mecatronico: {
    id: 'weapon_common_mecatronico',
    name: 'Lâmina Pesado Enferrujado',
    type: 'weapon',
    rarity: 'common',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {atk:10},
    value: 15,
  },
  weapon_common_eletromante: {
    id: 'weapon_common_eletromante',
    name: 'Rifle de Plasma Padrão',
    type: 'weapon',
    rarity: 'common',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {atk:4,mp:6},
    value: 15,
  },
  weapon_common_operador_drones: {
    id: 'weapon_common_operador_drones',
    name: 'Disparador de Precisão Usado',
    type: 'weapon',
    rarity: 'common',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {atk:6,spd:4},
    value: 15,
  },
  weapon_common_juggernaut_industrial: {
    id: 'weapon_common_juggernaut_industrial',
    name: 'Canhão Sísmico Genérico',
    type: 'weapon',
    rarity: 'common',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {atk:10},
    value: 15,
  },
  weapon_rare_classless_1: {
    id: 'weapon_rare_classless_1',
    name: 'Lâmina Reforçado',
    type: 'weapon',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {atk:35},
    value: 150,
  },
  weapon_rare_classless_2: {
    id: 'weapon_rare_classless_2',
    name: 'Rifle Militar',
    type: 'weapon',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {atk:35},
    value: 150,
  },
  weapon_rare_classless_3: {
    id: 'weapon_rare_classless_3',
    name: 'Disparador Avançado',
    type: 'weapon',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {atk:35},
    value: 150,
  },
  weapon_rare_tecno_aprendiz: {
    id: 'weapon_rare_tecno_aprendiz',
    name: 'Ferramenta de Manutenção Otimizado',
    type: 'weapon',
    rarity: 'rare',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {atk:35},
    value: 150,
  },
  weapon_rare_mecatronico: {
    id: 'weapon_rare_mecatronico',
    name: 'Lâmina Pesado Reforçado',
    type: 'weapon',
    rarity: 'rare',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {atk:35},
    value: 150,
  },
  weapon_rare_eletromante: {
    id: 'weapon_rare_eletromante',
    name: 'Rifle de Plasma Militar',
    type: 'weapon',
    rarity: 'rare',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {atk:14,mp:21},
    value: 150,
  },
  weapon_rare_operador_drones: {
    id: 'weapon_rare_operador_drones',
    name: 'Disparador de Precisão Avançado',
    type: 'weapon',
    rarity: 'rare',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {atk:21,spd:14},
    value: 150,
  },
  weapon_rare_juggernaut_industrial: {
    id: 'weapon_rare_juggernaut_industrial',
    name: 'Canhão Sísmico Customizado',
    type: 'weapon',
    rarity: 'rare',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {atk:35},
    value: 150,
  },
  weapon_epic_classless_1: {
    id: 'weapon_epic_classless_1',
    name: 'Lâmina Protótipo',
    type: 'weapon',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {atk:80},
    value: 500,
  },
  weapon_epic_classless_2: {
    id: 'weapon_epic_classless_2',
    name: 'Rifle Experimental',
    type: 'weapon',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {atk:80},
    value: 500,
  },
  weapon_epic_classless_3: {
    id: 'weapon_epic_classless_3',
    name: 'Disparador Sintético',
    type: 'weapon',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {atk:80},
    value: 500,
  },
  weapon_epic_tecno_aprendiz: {
    id: 'weapon_epic_tecno_aprendiz',
    name: 'Ferramenta de Manutenção Quântico',
    type: 'weapon',
    rarity: 'epic',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {atk:80},
    value: 500,
  },
  weapon_epic_mecatronico: {
    id: 'weapon_epic_mecatronico',
    name: 'Lâmina Pesado Protótipo',
    type: 'weapon',
    rarity: 'epic',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {atk:80},
    value: 500,
  },
  weapon_epic_eletromante: {
    id: 'weapon_epic_eletromante',
    name: 'Rifle de Plasma Experimental',
    type: 'weapon',
    rarity: 'epic',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {atk:32,mp:48},
    value: 500,
  },
  weapon_epic_operador_drones: {
    id: 'weapon_epic_operador_drones',
    name: 'Disparador de Precisão Sintético',
    type: 'weapon',
    rarity: 'epic',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {atk:48,spd:32},
    value: 500,
  },
  weapon_epic_juggernaut_industrial: {
    id: 'weapon_epic_juggernaut_industrial',
    name: 'Canhão Sísmico Obsoleto e Letal',
    type: 'weapon',
    rarity: 'epic',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {atk:80},
    value: 500,
  },
  // --- ARMOR ---
  armor_common_classless_1: {
    id: 'armor_common_classless_1',
    name: 'Placa Enferrujado',
    type: 'armor',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  armor_common_classless_2: {
    id: 'armor_common_classless_2',
    name: 'Colete Padrão',
    type: 'armor',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  armor_common_classless_3: {
    id: 'armor_common_classless_3',
    name: 'Chassi Usado',
    type: 'armor',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  armor_common_tecno_aprendiz: {
    id: 'armor_common_tecno_aprendiz',
    name: 'Macacão Simples Sucateado',
    type: 'armor',
    rarity: 'common',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  armor_common_mecatronico: {
    id: 'armor_common_mecatronico',
    name: 'Placa Reforçado Enferrujado',
    type: 'armor',
    rarity: 'common',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:7,hp:15},
    value: 15,
  },
  armor_common_eletromante: {
    id: 'armor_common_eletromante',
    name: 'Colete Isolante Padrão',
    type: 'armor',
    rarity: 'common',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  armor_common_operador_drones: {
    id: 'armor_common_operador_drones',
    name: 'Chassi Tático Usado',
    type: 'armor',
    rarity: 'common',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  armor_common_juggernaut_industrial: {
    id: 'armor_common_juggernaut_industrial',
    name: 'Blindagem Impenetrável Genérico',
    type: 'armor',
    rarity: 'common',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:7,hp:15},
    value: 15,
  },
  armor_rare_classless_1: {
    id: 'armor_rare_classless_1',
    name: 'Placa Reforçado',
    type: 'armor',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  armor_rare_classless_2: {
    id: 'armor_rare_classless_2',
    name: 'Colete Militar',
    type: 'armor',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  armor_rare_classless_3: {
    id: 'armor_rare_classless_3',
    name: 'Chassi Avançado',
    type: 'armor',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  armor_rare_tecno_aprendiz: {
    id: 'armor_rare_tecno_aprendiz',
    name: 'Macacão Simples Otimizado',
    type: 'armor',
    rarity: 'rare',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  armor_rare_mecatronico: {
    id: 'armor_rare_mecatronico',
    name: 'Placa Reforçado Reforçado',
    type: 'armor',
    rarity: 'rare',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:24,hp:50,spd:-3},
    value: 150,
  },
  armor_rare_eletromante: {
    id: 'armor_rare_eletromante',
    name: 'Colete Isolante Militar',
    type: 'armor',
    rarity: 'rare',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  armor_rare_operador_drones: {
    id: 'armor_rare_operador_drones',
    name: 'Chassi Tático Avançado',
    type: 'armor',
    rarity: 'rare',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  armor_rare_juggernaut_industrial: {
    id: 'armor_rare_juggernaut_industrial',
    name: 'Blindagem Impenetrável Customizado',
    type: 'armor',
    rarity: 'rare',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:24,hp:50,spd:-3},
    value: 150,
  },
  armor_epic_classless_1: {
    id: 'armor_epic_classless_1',
    name: 'Placa Protótipo',
    type: 'armor',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  armor_epic_classless_2: {
    id: 'armor_epic_classless_2',
    name: 'Colete Experimental',
    type: 'armor',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  armor_epic_classless_3: {
    id: 'armor_epic_classless_3',
    name: 'Chassi Sintético',
    type: 'armor',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  armor_epic_tecno_aprendiz: {
    id: 'armor_epic_tecno_aprendiz',
    name: 'Macacão Simples Quântico',
    type: 'armor',
    rarity: 'epic',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  armor_epic_mecatronico: {
    id: 'armor_epic_mecatronico',
    name: 'Placa Reforçado Protótipo',
    type: 'armor',
    rarity: 'epic',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:56,hp:120,spd:-8},
    value: 500,
  },
  armor_epic_eletromante: {
    id: 'armor_epic_eletromante',
    name: 'Colete Isolante Experimental',
    type: 'armor',
    rarity: 'epic',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  armor_epic_operador_drones: {
    id: 'armor_epic_operador_drones',
    name: 'Chassi Tático Sintético',
    type: 'armor',
    rarity: 'epic',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  armor_epic_juggernaut_industrial: {
    id: 'armor_epic_juggernaut_industrial',
    name: 'Blindagem Impenetrável Obsoleto e Letal',
    type: 'armor',
    rarity: 'epic',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:56,hp:120,spd:-8},
    value: 500,
  },
  // --- HELMET ---
  helmet_common_classless_1: {
    id: 'helmet_common_classless_1',
    name: 'Visor Enferrujado',
    type: 'helmet',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  helmet_common_classless_2: {
    id: 'helmet_common_classless_2',
    name: 'Máscara Padrão',
    type: 'helmet',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  helmet_common_classless_3: {
    id: 'helmet_common_classless_3',
    name: 'Coroa Usado',
    type: 'helmet',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  helmet_common_tecno_aprendiz: {
    id: 'helmet_common_tecno_aprendiz',
    name: 'Capacete de Operário Sucateado',
    type: 'helmet',
    rarity: 'common',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  helmet_common_mecatronico: {
    id: 'helmet_common_mecatronico',
    name: 'Visor Soldado Enferrujado',
    type: 'helmet',
    rarity: 'common',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:7,hp:15},
    value: 15,
  },
  helmet_common_eletromante: {
    id: 'helmet_common_eletromante',
    name: 'Máscara Neural Padrão',
    type: 'helmet',
    rarity: 'common',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  helmet_common_operador_drones: {
    id: 'helmet_common_operador_drones',
    name: 'Coroa HUD Usado',
    type: 'helmet',
    rarity: 'common',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  helmet_common_juggernaut_industrial: {
    id: 'helmet_common_juggernaut_industrial',
    name: 'Interface Titan Genérico',
    type: 'helmet',
    rarity: 'common',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:7,hp:15},
    value: 15,
  },
  helmet_rare_classless_1: {
    id: 'helmet_rare_classless_1',
    name: 'Visor Reforçado',
    type: 'helmet',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  helmet_rare_classless_2: {
    id: 'helmet_rare_classless_2',
    name: 'Máscara Militar',
    type: 'helmet',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  helmet_rare_classless_3: {
    id: 'helmet_rare_classless_3',
    name: 'Coroa Avançado',
    type: 'helmet',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  helmet_rare_tecno_aprendiz: {
    id: 'helmet_rare_tecno_aprendiz',
    name: 'Capacete de Operário Otimizado',
    type: 'helmet',
    rarity: 'rare',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  helmet_rare_mecatronico: {
    id: 'helmet_rare_mecatronico',
    name: 'Visor Soldado Reforçado',
    type: 'helmet',
    rarity: 'rare',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:24,hp:50,spd:-3},
    value: 150,
  },
  helmet_rare_eletromante: {
    id: 'helmet_rare_eletromante',
    name: 'Máscara Neural Militar',
    type: 'helmet',
    rarity: 'rare',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  helmet_rare_operador_drones: {
    id: 'helmet_rare_operador_drones',
    name: 'Coroa HUD Avançado',
    type: 'helmet',
    rarity: 'rare',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  helmet_rare_juggernaut_industrial: {
    id: 'helmet_rare_juggernaut_industrial',
    name: 'Interface Titan Customizado',
    type: 'helmet',
    rarity: 'rare',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:24,hp:50,spd:-3},
    value: 150,
  },
  helmet_epic_classless_1: {
    id: 'helmet_epic_classless_1',
    name: 'Visor Protótipo',
    type: 'helmet',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  helmet_epic_classless_2: {
    id: 'helmet_epic_classless_2',
    name: 'Máscara Experimental',
    type: 'helmet',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  helmet_epic_classless_3: {
    id: 'helmet_epic_classless_3',
    name: 'Coroa Sintético',
    type: 'helmet',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  helmet_epic_tecno_aprendiz: {
    id: 'helmet_epic_tecno_aprendiz',
    name: 'Capacete de Operário Quântico',
    type: 'helmet',
    rarity: 'epic',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  helmet_epic_mecatronico: {
    id: 'helmet_epic_mecatronico',
    name: 'Visor Soldado Protótipo',
    type: 'helmet',
    rarity: 'epic',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:56,hp:120,spd:-8},
    value: 500,
  },
  helmet_epic_eletromante: {
    id: 'helmet_epic_eletromante',
    name: 'Máscara Neural Experimental',
    type: 'helmet',
    rarity: 'epic',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  helmet_epic_operador_drones: {
    id: 'helmet_epic_operador_drones',
    name: 'Coroa HUD Sintético',
    type: 'helmet',
    rarity: 'epic',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  helmet_epic_juggernaut_industrial: {
    id: 'helmet_epic_juggernaut_industrial',
    name: 'Interface Titan Obsoleto e Letal',
    type: 'helmet',
    rarity: 'epic',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:56,hp:120,spd:-8},
    value: 500,
  },
  // --- PANTS ---
  pants_common_classless_1: {
    id: 'pants_common_classless_1',
    name: 'Perneira Enferrujado',
    type: 'pants',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  pants_common_classless_2: {
    id: 'pants_common_classless_2',
    name: 'Grevas Padrão',
    type: 'pants',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  pants_common_classless_3: {
    id: 'pants_common_classless_3',
    name: 'Protetor Usado',
    type: 'pants',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  pants_common_tecno_aprendiz: {
    id: 'pants_common_tecno_aprendiz',
    name: 'Calça Utilitária Sucateado',
    type: 'pants',
    rarity: 'common',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  pants_common_mecatronico: {
    id: 'pants_common_mecatronico',
    name: 'Perneira Hidráulica Enferrujado',
    type: 'pants',
    rarity: 'common',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:7,hp:15},
    value: 15,
  },
  pants_common_eletromante: {
    id: 'pants_common_eletromante',
    name: 'Grevas Antiestática Padrão',
    type: 'pants',
    rarity: 'common',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  pants_common_operador_drones: {
    id: 'pants_common_operador_drones',
    name: 'Protetor Ágil Usado',
    type: 'pants',
    rarity: 'common',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:6,hp:8},
    value: 15,
  },
  pants_common_juggernaut_industrial: {
    id: 'pants_common_juggernaut_industrial',
    name: 'Chassi Inferior Massiva Genérico',
    type: 'pants',
    rarity: 'common',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:7,hp:15},
    value: 15,
  },
  pants_rare_classless_1: {
    id: 'pants_rare_classless_1',
    name: 'Perneira Reforçado',
    type: 'pants',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  pants_rare_classless_2: {
    id: 'pants_rare_classless_2',
    name: 'Grevas Militar',
    type: 'pants',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  pants_rare_classless_3: {
    id: 'pants_rare_classless_3',
    name: 'Protetor Avançado',
    type: 'pants',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  pants_rare_tecno_aprendiz: {
    id: 'pants_rare_tecno_aprendiz',
    name: 'Calça Utilitária Otimizado',
    type: 'pants',
    rarity: 'rare',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  pants_rare_mecatronico: {
    id: 'pants_rare_mecatronico',
    name: 'Perneira Hidráulica Reforçado',
    type: 'pants',
    rarity: 'rare',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:24,hp:50,spd:-3},
    value: 150,
  },
  pants_rare_eletromante: {
    id: 'pants_rare_eletromante',
    name: 'Grevas Antiestática Militar',
    type: 'pants',
    rarity: 'rare',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  pants_rare_operador_drones: {
    id: 'pants_rare_operador_drones',
    name: 'Protetor Ágil Avançado',
    type: 'pants',
    rarity: 'rare',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:21,hp:28},
    value: 150,
  },
  pants_rare_juggernaut_industrial: {
    id: 'pants_rare_juggernaut_industrial',
    name: 'Chassi Inferior Massiva Customizado',
    type: 'pants',
    rarity: 'rare',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:24,hp:50,spd:-3},
    value: 150,
  },
  pants_epic_classless_1: {
    id: 'pants_epic_classless_1',
    name: 'Perneira Protótipo',
    type: 'pants',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  pants_epic_classless_2: {
    id: 'pants_epic_classless_2',
    name: 'Grevas Experimental',
    type: 'pants',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  pants_epic_classless_3: {
    id: 'pants_epic_classless_3',
    name: 'Protetor Sintético',
    type: 'pants',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  pants_epic_tecno_aprendiz: {
    id: 'pants_epic_tecno_aprendiz',
    name: 'Calça Utilitária Quântico',
    type: 'pants',
    rarity: 'epic',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  pants_epic_mecatronico: {
    id: 'pants_epic_mecatronico',
    name: 'Perneira Hidráulica Protótipo',
    type: 'pants',
    rarity: 'epic',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:56,hp:120,spd:-8},
    value: 500,
  },
  pants_epic_eletromante: {
    id: 'pants_epic_eletromante',
    name: 'Grevas Antiestática Experimental',
    type: 'pants',
    rarity: 'epic',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  pants_epic_operador_drones: {
    id: 'pants_epic_operador_drones',
    name: 'Protetor Ágil Sintético',
    type: 'pants',
    rarity: 'epic',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:48,hp:64},
    value: 500,
  },
  pants_epic_juggernaut_industrial: {
    id: 'pants_epic_juggernaut_industrial',
    name: 'Chassi Inferior Massiva Obsoleto e Letal',
    type: 'pants',
    rarity: 'epic',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:56,hp:120,spd:-8},
    value: 500,
  },
  // --- BOOTS ---
  boots_common_classless_1: {
    id: 'boots_common_classless_1',
    name: 'Propulsor Enferrujado',
    type: 'boots',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {spd:8,def:2},
    value: 15,
  },
  boots_common_classless_2: {
    id: 'boots_common_classless_2',
    name: 'Pisante Padrão',
    type: 'boots',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {spd:8,def:2},
    value: 15,
  },
  boots_common_classless_3: {
    id: 'boots_common_classless_3',
    name: 'Solado Usado',
    type: 'boots',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {spd:8,def:2},
    value: 15,
  },
  boots_common_tecno_aprendiz: {
    id: 'boots_common_tecno_aprendiz',
    name: 'Bota de Borracha Sucateado',
    type: 'boots',
    rarity: 'common',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {spd:8,def:2},
    value: 15,
  },
  boots_common_mecatronico: {
    id: 'boots_common_mecatronico',
    name: 'Propulsor Magnético Enferrujado',
    type: 'boots',
    rarity: 'common',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {spd:8,def:2},
    value: 15,
  },
  boots_common_eletromante: {
    id: 'boots_common_eletromante',
    name: 'Pisante Aterrador Padrão',
    type: 'boots',
    rarity: 'common',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {spd:8,def:2},
    value: 15,
  },
  boots_common_operador_drones: {
    id: 'boots_common_operador_drones',
    name: 'Solado Anti-Grav Usado',
    type: 'boots',
    rarity: 'common',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {spd:8,def:2},
    value: 15,
  },
  boots_common_juggernaut_industrial: {
    id: 'boots_common_juggernaut_industrial',
    name: 'Estabilizador de Ancoragem Genérico',
    type: 'boots',
    rarity: 'common',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {spd:8,def:2},
    value: 15,
  },
  boots_rare_classless_1: {
    id: 'boots_rare_classless_1',
    name: 'Propulsor Reforçado',
    type: 'boots',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {spd:28,def:7},
    value: 150,
  },
  boots_rare_classless_2: {
    id: 'boots_rare_classless_2',
    name: 'Pisante Militar',
    type: 'boots',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {spd:28,def:7},
    value: 150,
  },
  boots_rare_classless_3: {
    id: 'boots_rare_classless_3',
    name: 'Solado Avançado',
    type: 'boots',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {spd:28,def:7},
    value: 150,
  },
  boots_rare_tecno_aprendiz: {
    id: 'boots_rare_tecno_aprendiz',
    name: 'Bota de Borracha Otimizado',
    type: 'boots',
    rarity: 'rare',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {spd:28,def:7},
    value: 150,
  },
  boots_rare_mecatronico: {
    id: 'boots_rare_mecatronico',
    name: 'Propulsor Magnético Reforçado',
    type: 'boots',
    rarity: 'rare',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {spd:28,def:7},
    value: 150,
  },
  boots_rare_eletromante: {
    id: 'boots_rare_eletromante',
    name: 'Pisante Aterrador Militar',
    type: 'boots',
    rarity: 'rare',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {spd:28,def:7},
    value: 150,
  },
  boots_rare_operador_drones: {
    id: 'boots_rare_operador_drones',
    name: 'Solado Anti-Grav Avançado',
    type: 'boots',
    rarity: 'rare',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {spd:28,def:7},
    value: 150,
  },
  boots_rare_juggernaut_industrial: {
    id: 'boots_rare_juggernaut_industrial',
    name: 'Estabilizador de Ancoragem Customizado',
    type: 'boots',
    rarity: 'rare',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {spd:28,def:7},
    value: 150,
  },
  boots_epic_classless_1: {
    id: 'boots_epic_classless_1',
    name: 'Propulsor Protótipo',
    type: 'boots',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {spd:64,def:16},
    value: 500,
  },
  boots_epic_classless_2: {
    id: 'boots_epic_classless_2',
    name: 'Pisante Experimental',
    type: 'boots',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {spd:64,def:16},
    value: 500,
  },
  boots_epic_classless_3: {
    id: 'boots_epic_classless_3',
    name: 'Solado Sintético',
    type: 'boots',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {spd:64,def:16},
    value: 500,
  },
  boots_epic_tecno_aprendiz: {
    id: 'boots_epic_tecno_aprendiz',
    name: 'Bota de Borracha Quântico',
    type: 'boots',
    rarity: 'epic',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {spd:64,def:16},
    value: 500,
  },
  boots_epic_mecatronico: {
    id: 'boots_epic_mecatronico',
    name: 'Propulsor Magnético Protótipo',
    type: 'boots',
    rarity: 'epic',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {spd:64,def:16},
    value: 500,
  },
  boots_epic_eletromante: {
    id: 'boots_epic_eletromante',
    name: 'Pisante Aterrador Experimental',
    type: 'boots',
    rarity: 'epic',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {spd:64,def:16},
    value: 500,
  },
  boots_epic_operador_drones: {
    id: 'boots_epic_operador_drones',
    name: 'Solado Anti-Grav Sintético',
    type: 'boots',
    rarity: 'epic',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {spd:64,def:16},
    value: 500,
  },
  boots_epic_juggernaut_industrial: {
    id: 'boots_epic_juggernaut_industrial',
    name: 'Estabilizador de Ancoragem Obsoleto e Letal',
    type: 'boots',
    rarity: 'epic',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {spd:64,def:16},
    value: 500,
  },
  // --- BRACERS ---
  bracers_common_classless_1: {
    id: 'bracers_common_classless_1',
    name: 'Luva Enferrujado',
    type: 'bracers',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:5,atk:5},
    value: 15,
  },
  bracers_common_classless_2: {
    id: 'bracers_common_classless_2',
    name: 'Manopla Padrão',
    type: 'bracers',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:5,atk:5},
    value: 15,
  },
  bracers_common_classless_3: {
    id: 'bracers_common_classless_3',
    name: 'Protetor de Pulso Usado',
    type: 'bracers',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {def:5,atk:5},
    value: 15,
  },
  bracers_common_tecno_aprendiz: {
    id: 'bracers_common_tecno_aprendiz',
    name: 'Braçadeira Térmica Sucateado',
    type: 'bracers',
    rarity: 'common',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:5,atk:5},
    value: 15,
  },
  bracers_common_mecatronico: {
    id: 'bracers_common_mecatronico',
    name: 'Luva Cinética Enferrujado',
    type: 'bracers',
    rarity: 'common',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:5,atk:5},
    value: 15,
  },
  bracers_common_eletromante: {
    id: 'bracers_common_eletromante',
    name: 'Manopla Condutora Padrão',
    type: 'bracers',
    rarity: 'common',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:5,atk:5},
    value: 15,
  },
  bracers_common_operador_drones: {
    id: 'bracers_common_operador_drones',
    name: 'Protetor de Pulso Biométrica Usado',
    type: 'bracers',
    rarity: 'common',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:5,atk:5},
    value: 15,
  },
  bracers_common_juggernaut_industrial: {
    id: 'bracers_common_juggernaut_industrial',
    name: 'Exo-Braço Esmagadora Genérico',
    type: 'bracers',
    rarity: 'common',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:5,atk:5},
    value: 15,
  },
  bracers_rare_classless_1: {
    id: 'bracers_rare_classless_1',
    name: 'Luva Reforçado',
    type: 'bracers',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:17,atk:17},
    value: 150,
  },
  bracers_rare_classless_2: {
    id: 'bracers_rare_classless_2',
    name: 'Manopla Militar',
    type: 'bracers',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:17,atk:17},
    value: 150,
  },
  bracers_rare_classless_3: {
    id: 'bracers_rare_classless_3',
    name: 'Protetor de Pulso Avançado',
    type: 'bracers',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {def:17,atk:17},
    value: 150,
  },
  bracers_rare_tecno_aprendiz: {
    id: 'bracers_rare_tecno_aprendiz',
    name: 'Braçadeira Térmica Otimizado',
    type: 'bracers',
    rarity: 'rare',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:17,atk:17},
    value: 150,
  },
  bracers_rare_mecatronico: {
    id: 'bracers_rare_mecatronico',
    name: 'Luva Cinética Reforçado',
    type: 'bracers',
    rarity: 'rare',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:17,atk:17},
    value: 150,
  },
  bracers_rare_eletromante: {
    id: 'bracers_rare_eletromante',
    name: 'Manopla Condutora Militar',
    type: 'bracers',
    rarity: 'rare',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:17,atk:17},
    value: 150,
  },
  bracers_rare_operador_drones: {
    id: 'bracers_rare_operador_drones',
    name: 'Protetor de Pulso Biométrica Avançado',
    type: 'bracers',
    rarity: 'rare',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:17,atk:17},
    value: 150,
  },
  bracers_rare_juggernaut_industrial: {
    id: 'bracers_rare_juggernaut_industrial',
    name: 'Exo-Braço Esmagadora Customizado',
    type: 'bracers',
    rarity: 'rare',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:17,atk:17},
    value: 150,
  },
  bracers_epic_classless_1: {
    id: 'bracers_epic_classless_1',
    name: 'Luva Protótipo',
    type: 'bracers',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:40,atk:40},
    value: 500,
  },
  bracers_epic_classless_2: {
    id: 'bracers_epic_classless_2',
    name: 'Manopla Experimental',
    type: 'bracers',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:40,atk:40},
    value: 500,
  },
  bracers_epic_classless_3: {
    id: 'bracers_epic_classless_3',
    name: 'Protetor de Pulso Sintético',
    type: 'bracers',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {def:40,atk:40},
    value: 500,
  },
  bracers_epic_tecno_aprendiz: {
    id: 'bracers_epic_tecno_aprendiz',
    name: 'Braçadeira Térmica Quântico',
    type: 'bracers',
    rarity: 'epic',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {def:40,atk:40},
    value: 500,
  },
  bracers_epic_mecatronico: {
    id: 'bracers_epic_mecatronico',
    name: 'Luva Cinética Protótipo',
    type: 'bracers',
    rarity: 'epic',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {def:40,atk:40},
    value: 500,
  },
  bracers_epic_eletromante: {
    id: 'bracers_epic_eletromante',
    name: 'Manopla Condutora Experimental',
    type: 'bracers',
    rarity: 'epic',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {def:40,atk:40},
    value: 500,
  },
  bracers_epic_operador_drones: {
    id: 'bracers_epic_operador_drones',
    name: 'Protetor de Pulso Biométrica Sintético',
    type: 'bracers',
    rarity: 'epic',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {def:40,atk:40},
    value: 500,
  },
  bracers_epic_juggernaut_industrial: {
    id: 'bracers_epic_juggernaut_industrial',
    name: 'Exo-Braço Esmagadora Obsoleto e Letal',
    type: 'bracers',
    rarity: 'epic',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {def:40,atk:40},
    value: 500,
  },
  // --- ACCESSORY ---
  accessory_common_classless_1: {
    id: 'accessory_common_classless_1',
    name: 'Núcleo Enferrujado',
    type: 'accessory',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {hp:15,mp:10},
    value: 15,
  },
  accessory_common_classless_2: {
    id: 'accessory_common_classless_2',
    name: 'Chip Padrão',
    type: 'accessory',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {hp:15,mp:10},
    value: 15,
  },
  accessory_common_classless_3: {
    id: 'accessory_common_classless_3',
    name: 'Módulo Usado',
    type: 'accessory',
    rarity: 'common',
    description: 'Equipamento universal common.',
    allowedClassIds: [],
    statModifiers: {hp:15,mp:10},
    value: 15,
  },
  accessory_common_tecno_aprendiz: {
    id: 'accessory_common_tecno_aprendiz',
    name: 'Bateria de Backup Sucateado',
    type: 'accessory',
    rarity: 'common',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {hp:15,mp:10},
    value: 15,
  },
  accessory_common_mecatronico: {
    id: 'accessory_common_mecatronico',
    name: 'Núcleo de Sobrecarga Enferrujado',
    type: 'accessory',
    rarity: 'common',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {hp:15,mp:10},
    value: 15,
  },
  accessory_common_eletromante: {
    id: 'accessory_common_eletromante',
    name: 'Chip de Fissão Padrão',
    type: 'accessory',
    rarity: 'common',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {hp:15,mp:10},
    value: 15,
  },
  accessory_common_operador_drones: {
    id: 'accessory_common_operador_drones',
    name: 'Módulo Radar Usado',
    type: 'accessory',
    rarity: 'common',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {hp:15,mp:10},
    value: 15,
  },
  accessory_common_juggernaut_industrial: {
    id: 'accessory_common_juggernaut_industrial',
    name: 'Sensor Reator Genérico',
    type: 'accessory',
    rarity: 'common',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {hp:15,mp:10},
    value: 15,
  },
  accessory_rare_classless_1: {
    id: 'accessory_rare_classless_1',
    name: 'Núcleo Reforçado',
    type: 'accessory',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {hp:51,mp:34},
    value: 150,
  },
  accessory_rare_classless_2: {
    id: 'accessory_rare_classless_2',
    name: 'Chip Militar',
    type: 'accessory',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {hp:51,mp:34},
    value: 150,
  },
  accessory_rare_classless_3: {
    id: 'accessory_rare_classless_3',
    name: 'Módulo Avançado',
    type: 'accessory',
    rarity: 'rare',
    description: 'Equipamento universal rare.',
    allowedClassIds: [],
    statModifiers: {hp:51,mp:34},
    value: 150,
  },
  accessory_rare_tecno_aprendiz: {
    id: 'accessory_rare_tecno_aprendiz',
    name: 'Bateria de Backup Otimizado',
    type: 'accessory',
    rarity: 'rare',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {hp:51,mp:34},
    value: 150,
  },
  accessory_rare_mecatronico: {
    id: 'accessory_rare_mecatronico',
    name: 'Núcleo de Sobrecarga Reforçado',
    type: 'accessory',
    rarity: 'rare',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {hp:51,mp:34},
    value: 150,
  },
  accessory_rare_eletromante: {
    id: 'accessory_rare_eletromante',
    name: 'Chip de Fissão Militar',
    type: 'accessory',
    rarity: 'rare',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {hp:51,mp:34},
    value: 150,
  },
  accessory_rare_operador_drones: {
    id: 'accessory_rare_operador_drones',
    name: 'Módulo Radar Avançado',
    type: 'accessory',
    rarity: 'rare',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {hp:51,mp:34},
    value: 150,
  },
  accessory_rare_juggernaut_industrial: {
    id: 'accessory_rare_juggernaut_industrial',
    name: 'Sensor Reator Customizado',
    type: 'accessory',
    rarity: 'rare',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {hp:51,mp:34},
    value: 150,
  },
  accessory_epic_classless_1: {
    id: 'accessory_epic_classless_1',
    name: 'Núcleo Protótipo',
    type: 'accessory',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {hp:120,mp:80},
    value: 500,
  },
  accessory_epic_classless_2: {
    id: 'accessory_epic_classless_2',
    name: 'Chip Experimental',
    type: 'accessory',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {hp:120,mp:80},
    value: 500,
  },
  accessory_epic_classless_3: {
    id: 'accessory_epic_classless_3',
    name: 'Módulo Sintético',
    type: 'accessory',
    rarity: 'epic',
    description: 'Equipamento universal epic.',
    allowedClassIds: [],
    statModifiers: {hp:120,mp:80},
    value: 500,
  },
  accessory_epic_tecno_aprendiz: {
    id: 'accessory_epic_tecno_aprendiz',
    name: 'Bateria de Backup Quântico',
    type: 'accessory',
    rarity: 'epic',
    description: 'Hardware especializado para tecno_aprendiz.',
    allowedClassIds: ['tecno_aprendiz'],
    statModifiers: {hp:120,mp:80},
    value: 500,
  },
  accessory_epic_mecatronico: {
    id: 'accessory_epic_mecatronico',
    name: 'Núcleo de Sobrecarga Protótipo',
    type: 'accessory',
    rarity: 'epic',
    description: 'Hardware especializado para mecatronico.',
    allowedClassIds: ['mecatronico'],
    statModifiers: {hp:120,mp:80},
    value: 500,
  },
  accessory_epic_eletromante: {
    id: 'accessory_epic_eletromante',
    name: 'Chip de Fissão Experimental',
    type: 'accessory',
    rarity: 'epic',
    description: 'Hardware especializado para eletromante.',
    allowedClassIds: ['eletromante'],
    statModifiers: {hp:120,mp:80},
    value: 500,
  },
  accessory_epic_operador_drones: {
    id: 'accessory_epic_operador_drones',
    name: 'Módulo Radar Sintético',
    type: 'accessory',
    rarity: 'epic',
    description: 'Hardware especializado para operador_drones.',
    allowedClassIds: ['operador_drones'],
    statModifiers: {hp:120,mp:80},
    value: 500,
  },
  accessory_epic_juggernaut_industrial: {
    id: 'accessory_epic_juggernaut_industrial',
    name: 'Sensor Reator Obsoleto e Letal',
    type: 'accessory',
    rarity: 'epic',
    description: 'Hardware especializado para juggernaut_industrial.',
    allowedClassIds: ['juggernaut_industrial'],
    statModifiers: {hp:120,mp:80},
    value: 500,
  },
};
export function canClassEquipItem(playerClassId: string, item: Item): boolean {
  // Se não houver restrição, permite
  if (!item.allowedClassIds || item.allowedClassIds.length === 0) {
    return true;
  }

  let currentClass: ClassDefinition | undefined = CLASSES[playerClassId];

  // Percorre a árvore de classes de baixo para cima
  while (currentClass) {
    if (item.allowedClassIds.includes(currentClass.id)) {
      return true; // Encontrou permissão nesta classe ou em algum ancestral
    }
    
    // Sobe para o parent
    if (currentClass.parentClassId) {
      currentClass = CLASSES[currentClass.parentClassId];
    } else {
      break;
    }
  }

  return false;
}

export function getRandomItemByRarityAndClass(rarity: Rarity, classId: string): Item | null {
  const pool = Object.values(ITEMS_DATABASE).filter(item => 
    item.rarity === rarity && canClassEquipItem(classId, item)
  );

  if (pool.length === 0) return null;
  const item = pool[Math.floor(random() * pool.length)];
  return applyManufacturer(item);
}

/**
 * Retorna um item aleatório baseado em uma determinada raridade.
 */
export function getRandomItemByRarity(rarity: Rarity): Item | null {
  const items = Object.values(ITEMS_DATABASE).filter(i => i.rarity === rarity);
  if (items.length === 0) return null;
  const index = Math.floor(random() * items.length);
  return items[index];
}

export function getItemTier(item: Item): number {
  if (!item.allowedClassIds || item.allowedClassIds.length === 0) return 1;
  let maxLevel = 1;
  for (const classId of item.allowedClassIds) {
    const classDef = CLASSES[classId];
    if (classDef && classDef.requiredLevel > maxLevel) {
      maxLevel = classDef.requiredLevel;
    }
  }
  return maxLevel;
}

export function getRandomItemForFloor(rarity: Rarity, floor: number): Item | null {
  const itemsOfRarity = Object.values(ITEMS_DATABASE).filter(i => i.rarity === rarity);
  if (itemsOfRarity.length === 0) return null;

  const weightedItems = itemsOfRarity.map(item => {
    const tier = getItemTier(item);
    const diff = floor - tier;
    let weight = 10;
    
    if (diff < 0) {
       weight = Math.max(1, Math.floor(10 / Math.abs(diff)));
    } else if (diff < 20) {
       weight = 20 + diff * 4;
    } else if (diff < 40) {
       weight = 100;
    } else {
       weight = Math.max(5, 100 - (diff - 40) * 2);
    }
    
    return { item, weight };
  });

  const validItems = weightedItems.filter(i => i.weight > 0);
  if (validItems.length === 0) {
    const index = Math.floor(random() * itemsOfRarity.length);
    return applyManufacturer(itemsOfRarity[index]);
  }

  const totalWeight = validItems.reduce((acc, curr) => acc + curr.weight, 0);
  let roll = random() * totalWeight;

  for (const { item, weight } of validItems) {
    roll -= weight;
    if (roll <= 0) return applyManufacturer(item);
  }

  return applyManufacturer(validItems[validItems.length - 1].item);
}
